name: Self-Hosted Runner Workflow

on: [push]

jobs:
  build:
    runs-on: self-hosted  # This ensures the job runs on your self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a script on the runner
      run: |
        echo "Hello from the self-hosted runner!"
        npm install
        pm2 start "npm start"
        sonar-scanner \
        -Dsonar.projectKey=lockel \
        -Dsonar.sources=. \
        -Dsonar.host.url=http://localhost:3000 \
        -Dsonar.token=sqp_adb9f247dbbcbb2b41a4cda26de04fba02c95ddb
